-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 14:28:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema championschallengeproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema championschallengeproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `championschallengeproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `championschallengeproject` ;

-- -----------------------------------------------------
-- Table `championschallengeproject`.`clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`clubs` (
  `id_club` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `club_code` VARCHAR(3) NOT NULL,
  `country_code` VARCHAR(3) NOT NULL,
  `group` VARCHAR(3) NOT NULL,
  `rate` INT(11) NOT NULL,
  PRIMARY KEY (`id_club`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`leagues` (
  `id_league` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `ranking` INT(11) NOT NULL,
  PRIMARY KEY (`id_league`),
  UNIQUE INDEX `idleague_UNIQUE` (`id_league` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`match_of_ze_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`match_of_ze_day` (
  `id_match_of_the_day` INT(11) NOT NULL,
  `match 1` INT(11) NULL DEFAULT NULL,
  `match 2` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_match_of_the_day`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`players` (
  `id_player` INT(11) NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `position` VARCHAR(10) NOT NULL,
  `position_code` VARCHAR(3) NOT NULL,
  `country_code` VARCHAR(3) NOT NULL,
  `club` VARCHAR(20) NOT NULL,
  `id_club` INT(11) NOT NULL,
  `value` INT(11) NOT NULL,
  PRIMARY KEY (`id_player`),
  INDEX `fk_players_clubs` (`id_club` ASC) VISIBLE,
  CONSTRAINT `fk_players_clubs`
    FOREIGN KEY (`id_club`)
    REFERENCES `championschallengeproject`.`clubs` (`id_club`))
ENGINE = InnoDB
AUTO_INCREMENT = 337
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`users` (
  `id_user` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `security_request` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`teams` (
  `id_teams` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id_user` INT(11) NOT NULL,
  `players_id_player` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `users_id_user1` INT(11) NOT NULL,
  INDEX `fk_users_has_joueurs_users1_idx` (`users_id_user` ASC) VISIBLE,
  INDEX `fk_teams_users1_idx` (`users_id_user1` ASC) VISIBLE,
  PRIMARY KEY (`id_teams`),
  CONSTRAINT `fk_teams_users`
    FOREIGN KEY (`users_id_user1`)
    REFERENCES `championschallengeproject`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`teams_have_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`teams_have_players` (
  `id_teams_have_players` INT(11) NOT NULL AUTO_INCREMENT,
  `players_id_player` INT(11) NOT NULL,
  `teams_id_teams` INT(11) NOT NULL,
  PRIMARY KEY (`id_teams_have_players`),
  INDEX `fk_players_has_teams_teams1_idx` (`teams_id_teams` ASC) VISIBLE,
  INDEX `fk_players_has_teams_players1_idx` (`players_id_player` ASC) VISIBLE,
  CONSTRAINT `fk_thp_players`
    FOREIGN KEY (`players_id_player`)
    REFERENCES `championschallengeproject`.`players` (`id_player`),
  CONSTRAINT `fk_thp_teams`
    FOREIGN KEY (`teams_id_teams`)
    REFERENCES `championschallengeproject`.`teams` (`users_id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`results_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`results_users` (
  `id_results_users` INT(11) NOT NULL AUTO_INCREMENT,
  `league_id_league` INT(11) NOT NULL,
  `match_of_ze_day_id_match_of_the_day` INT(11) NOT NULL,
  `match 1` INT(11) NULL DEFAULT NULL,
  `match 2` INT(11) NULL DEFAULT NULL,
  INDEX `fk_ligues_has_journeeMatch_journeeMatch1_idx` (`match_of_ze_day_id_match_of_the_day` ASC) VISIBLE,
  INDEX `fk_ligues_has_journeeMatch_ligues1_idx` (`league_id_league` ASC) VISIBLE,
  PRIMARY KEY (`id_results_users`),
  CONSTRAINT `fk_results_match`
    FOREIGN KEY (`match_of_ze_day_id_match_of_the_day`)
    REFERENCES `championschallengeproject`.`match_of_ze_day` (`id_match_of_the_day`),
  CONSTRAINT `fk_resuts_leagues`
    FOREIGN KEY (`league_id_league`)
    REFERENCES `championschallengeproject`.`leagues` (`id_league`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`stats_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`stats_players` (
  `id_stats_players` INT(11) NOT NULL AUTO_INCREMENT,
  `rates` INT(11) NULL DEFAULT NULL,
  `goals` INT(11) NOT NULL,
  `id_match_of_ze_day` INT(11) NOT NULL,
  `id_player` INT(11) NOT NULL,
  INDEX `Id_JourneeMatch_idx` (`id_match_of_ze_day` ASC) VISIBLE,
  INDEX `Id_Joueur_idx` (`id_player` ASC) VISIBLE,
  PRIMARY KEY (`id_stats_players`),
  CONSTRAINT `fk_stats_players`
    FOREIGN KEY (`id_player`)
    REFERENCES `championschallengeproject`.`players` (`id_player`),
  CONSTRAINT `fk_stats_match`
    FOREIGN KEY (`id_match_of_ze_day`)
    REFERENCES `championschallengeproject`.`match_of_ze_day` (`id_match_of_the_day`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`leagues_have_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`leagues_have_users` (
  `id_leagues_have_users` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id_user` INT(11) NOT NULL,
  `leagues_id_league` INT(11) NOT NULL,
  PRIMARY KEY (`id_leagues_have_users`),
  INDEX `fk_users_has_ligues_ligues1_idx` (`leagues_id_league` ASC) VISIBLE,
  INDEX `fk_users_has_ligues_users1_idx` (`users_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_lhu_leagues`
    FOREIGN KEY (`leagues_id_league`)
    REFERENCES `championschallengeproject`.`leagues` (`id_league`),
  CONSTRAINT `fk_lhu_users`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `championschallengeproject`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
