-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 09:35:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema championschallengeproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema championschallengeproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `championschallengeproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `championschallengeproject` ;

-- -----------------------------------------------------
-- Table `championschallengeproject`.`clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`clubs` (
  `id_club` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `club_code` VARCHAR(3) NOT NULL,
  `country_code` VARCHAR(3) NOT NULL,
  `group` VARCHAR(3) NOT NULL,
  `rate` INT(11) NOT NULL,
  PRIMARY KEY (`id_club`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`players` (
  `id_player` INT(11) NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `position` VARCHAR(10) NOT NULL,
  `position_code` VARCHAR(3) NOT NULL,
  `country_code` VARCHAR(3) NOT NULL,
  `club` VARCHAR(20) NOT NULL,
  `id_club` INT(11) NOT NULL,
  `value` INT(11) NOT NULL,
  PRIMARY KEY (`id_player`),
  INDEX `Id_Club` (`id_club` ASC) VISIBLE,
  CONSTRAINT `Id_Club`
    FOREIGN KEY (`id_club`)
    REFERENCES `championschallengeproject`.`clubs` (`id_club`))
ENGINE = InnoDB
AUTO_INCREMENT = 337
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`users` (
  `id_user` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `security_request` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`match_of_ze_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`match_of_ze_day` (
  `id_match_of_the_day` INT NOT NULL,
  `match 1` INT NULL,
  `match 2` INT NULL,
  PRIMARY KEY (`id_match_of_the_day`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`leagues` (
  `id_league` VARCHAR(5) NOT NULL,
  `name` INT NOT NULL,
  `ranking` INT NOT NULL,
  `users_Id_User` INT NOT NULL,
  PRIMARY KEY (`id_league`),
  UNIQUE INDEX `idleague_UNIQUE` (`id_league` ASC) VISIBLE,
  INDEX `fk_ligues_users1_idx` (`users_Id_User` ASC) VISIBLE,
  CONSTRAINT `fk_ligues_users1`
    FOREIGN KEY (`users_Id_User`)
    REFERENCES `championschallengeproject`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`stats_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`stats_players` (
  `rates` INT NULL,
  `goals` INT NOT NULL,
  `id_match_of_ze_day` INT NOT NULL,
  `id_player` INT NULL,
  INDEX `Id_JourneeMatch_idx` (`id_match_of_ze_day` ASC) VISIBLE,
  INDEX `Id_Joueur_idx` (`id_player` ASC) VISIBLE,
  CONSTRAINT `Id_JourneeMatch`
    FOREIGN KEY (`id_match_of_ze_day`)
    REFERENCES `championschallengeproject`.`match_of_ze_day` (`id_match_of_the_day`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Joueur`
    FOREIGN KEY (`id_player`)
    REFERENCES `championschallengeproject`.`players` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`users_has_ligues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`users_has_ligues` (
  `users_id_user` INT NOT NULL,
  `leagues_id_league` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`users_id_user`, `leagues_id_league`),
  INDEX `fk_users_has_ligues_ligues1_idx` (`leagues_id_league` ASC) VISIBLE,
  INDEX `fk_users_has_ligues_users1_idx` (`users_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_ligues_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `championschallengeproject`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_ligues_ligues1`
    FOREIGN KEY (`leagues_id_league`)
    REFERENCES `championschallengeproject`.`leagues` (`id_league`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`teams` (
  `users_id_user` INT NOT NULL,
  `players_id_player` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_id_user`, `players_id_player`),
  INDEX `fk_users_has_joueurs_joueurs1_idx` (`players_id_player` ASC) VISIBLE,
  INDEX `fk_users_has_joueurs_users1_idx` (`users_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_joueurs_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `championschallengeproject`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_joueurs_joueurs1`
    FOREIGN KEY (`players_id_player`)
    REFERENCES `championschallengeproject`.`players` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `championschallengeproject`.`results_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `championschallengeproject`.`results_users` (
  `league_id_league` VARCHAR(5) NOT NULL,
  `match_of_ze_day_id_match_of_the_day` INT NOT NULL,
  `match 1` INT NULL,
  `match 2` INT NULL,
  PRIMARY KEY (`league_id_league`, `match_of_ze_day_id_match_of_the_day`),
  INDEX `fk_ligues_has_journeeMatch_journeeMatch1_idx` (`match_of_ze_day_id_match_of_the_day` ASC) VISIBLE,
  INDEX `fk_ligues_has_journeeMatch_ligues1_idx` (`league_id_league` ASC) VISIBLE,
  CONSTRAINT `fk_ligues_has_journeeMatch_ligues1`
    FOREIGN KEY (`league_id_league`)
    REFERENCES `championschallengeproject`.`leagues` (`id_league`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligues_has_journeeMatch_journeeMatch1`
    FOREIGN KEY (`match_of_ze_day_id_match_of_the_day`)
    REFERENCES `championschallengeproject`.`match_of_ze_day` (`id_match_of_the_day`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
