package fr.formation.inti.entities;
// Generated 5 sept. 2019 14:30:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LeaguesHaveUsers generated by hbm2java
 */
@Entity
@Table(name = "leagues_have_users", catalog = "championschallengeproject")
public class LeaguesHaveUsers implements java.io.Serializable {

	private int idLeaguesHaveUsers;
	private Leagues leagues;
	private Users users;

	public LeaguesHaveUsers() {
	}

	public LeaguesHaveUsers(int idLeaguesHaveUsers, Leagues leagues, Users users) {
		this.idLeaguesHaveUsers = idLeaguesHaveUsers;
		this.leagues = leagues;
		this.users = users;
	}

	@Id

	@Column(name = "id_leagues_have_users", unique = true, nullable = false)
	public int getIdLeaguesHaveUsers() {
		return this.idLeaguesHaveUsers;
	}

	public void setIdLeaguesHaveUsers(int idLeaguesHaveUsers) {
		this.idLeaguesHaveUsers = idLeaguesHaveUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "leagues_id_league", nullable = false)
	public Leagues getLeagues() {
		return this.leagues;
	}

	public void setLeagues(Leagues leagues) {
		this.leagues = leagues;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id_user", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
