package fr.formation.inti.entities;
// Generated 5 sept. 2019 14:30:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StatsPlayers generated by hbm2java
 */
@Entity
@Table(name = "stats_players", catalog = "championschallengeproject")
public class StatsPlayers implements java.io.Serializable {

	private int idStatsPlayers;
	private MatchOfZeDay matchOfZeDay;
	private Players players;
	private Integer rates;
	private int goals;

	public StatsPlayers() {
	}

	public StatsPlayers(int idStatsPlayers, MatchOfZeDay matchOfZeDay, Players players, int goals) {
		this.idStatsPlayers = idStatsPlayers;
		this.matchOfZeDay = matchOfZeDay;
		this.players = players;
		this.goals = goals;
	}

	public StatsPlayers(int idStatsPlayers, MatchOfZeDay matchOfZeDay, Players players, Integer rates, int goals) {
		this.idStatsPlayers = idStatsPlayers;
		this.matchOfZeDay = matchOfZeDay;
		this.players = players;
		this.rates = rates;
		this.goals = goals;
	}

	@Id

	@Column(name = "id_stats_players", unique = true, nullable = false)
	public int getIdStatsPlayers() {
		return this.idStatsPlayers;
	}

	public void setIdStatsPlayers(int idStatsPlayers) {
		this.idStatsPlayers = idStatsPlayers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_match_of_ze_day", nullable = false)
	public MatchOfZeDay getMatchOfZeDay() {
		return this.matchOfZeDay;
	}

	public void setMatchOfZeDay(MatchOfZeDay matchOfZeDay) {
		this.matchOfZeDay = matchOfZeDay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_player", nullable = false)
	public Players getPlayers() {
		return this.players;
	}

	public void setPlayers(Players players) {
		this.players = players;
	}

	@Column(name = "rates")
	public Integer getRates() {
		return this.rates;
	}

	public void setRates(Integer rates) {
		this.rates = rates;
	}

	@Column(name = "goals", nullable = false)
	public int getGoals() {
		return this.goals;
	}

	public void setGoals(int goals) {
		this.goals = goals;
	}

}
