package fr.formation.inti.entities;
// Generated 5 sept. 2019 14:30:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teams generated by hbm2java
 */
@Entity
@Table(name = "teams", catalog = "championschallengeproject")
public class Teams implements java.io.Serializable {

	private int idTeams;
	private Users users;
	private int usersIdUser;
	private int playersIdPlayer;
	private String name;
	private Set<TeamsHavePlayers> teamsHavePlayerses = new HashSet<TeamsHavePlayers>(0);

	public Teams() {
	}

	public Teams(int idTeams, Users users, int usersIdUser, int playersIdPlayer, String name) {
		this.idTeams = idTeams;
		this.users = users;
		this.usersIdUser = usersIdUser;
		this.playersIdPlayer = playersIdPlayer;
		this.name = name;
	}

	public Teams(int idTeams, Users users, int usersIdUser, int playersIdPlayer, String name,
			Set<TeamsHavePlayers> teamsHavePlayerses) {
		this.idTeams = idTeams;
		this.users = users;
		this.usersIdUser = usersIdUser;
		this.playersIdPlayer = playersIdPlayer;
		this.name = name;
		this.teamsHavePlayerses = teamsHavePlayerses;
	}

	@Id

	@Column(name = "id_teams", unique = true, nullable = false)
	public int getIdTeams() {
		return this.idTeams;
	}

	public void setIdTeams(int idTeams) {
		this.idTeams = idTeams;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id_user1", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "users_id_user", nullable = false)
	public int getUsersIdUser() {
		return this.usersIdUser;
	}

	public void setUsersIdUser(int usersIdUser) {
		this.usersIdUser = usersIdUser;
	}

	@Column(name = "players_id_player", nullable = false)
	public int getPlayersIdPlayer() {
		return this.playersIdPlayer;
	}

	public void setPlayersIdPlayer(int playersIdPlayer) {
		this.playersIdPlayer = playersIdPlayer;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teams")
	public Set<TeamsHavePlayers> getTeamsHavePlayerses() {
		return this.teamsHavePlayerses;
	}

	public void setTeamsHavePlayerses(Set<TeamsHavePlayers> teamsHavePlayerses) {
		this.teamsHavePlayerses = teamsHavePlayerses;
	}

}
