package fr.formation.inti.entities;
// Generated 5 sept. 2019 14:30:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeamsHavePlayers generated by hbm2java
 */
@Entity
@Table(name = "teams_have_players", catalog = "championschallengeproject")
public class TeamsHavePlayers implements java.io.Serializable {

	private int idTeamsHavePlayers;
	private Players players;
	private Teams teams;

	public TeamsHavePlayers() {
	}

	public TeamsHavePlayers(int idTeamsHavePlayers, Players players, Teams teams) {
		this.idTeamsHavePlayers = idTeamsHavePlayers;
		this.players = players;
		this.teams = teams;
	}

	@Id

	@Column(name = "id_teams_have_players", unique = true, nullable = false)
	public int getIdTeamsHavePlayers() {
		return this.idTeamsHavePlayers;
	}

	public void setIdTeamsHavePlayers(int idTeamsHavePlayers) {
		this.idTeamsHavePlayers = idTeamsHavePlayers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "players_id_player", nullable = false)
	public Players getPlayers() {
		return this.players;
	}

	public void setPlayers(Players players) {
		this.players = players;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teams_id_teams", nullable = false)
	public Teams getTeams() {
		return this.teams;
	}

	public void setTeams(Teams teams) {
		this.teams = teams;
	}

}
